import { ClerkProvider } from '@clerk/nextjs'
import { Open_Sans } from "next/font/google";
import "./globals.css";

import NavBar from "../compontents/navigation";
import Footer from "../compontents/footer";

const opentSans = Open_Sans({
  weight: ["300","400","600", "700","800"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={opentSans.className}
        >
          <div className="fixed top-0 z-50 w-full">
            <NavBar/>
          </div>
          
          {children}
        
          <Footer/>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
